spring.application.name=registroReceitas
server.port=80

# --- Configuracao do Banco de Dados ---
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/registro_receitas_db
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:postgres}

# Ajuda o Hibernate (JPA) a "conversar" com o PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
