credentials:
  system:
    domainCredentials:
      - credentials:

jobs:
  - script: >
      pipelineJob('Registro-Receitas-Deploy-Pipeline') {
          description('Pipeline criada sozinha ao subir o container Docker.')
      
          definition {
              cpsScm {
                  scm {
                      git {
                          remote {
                              url('https://github.com/Arthwh/task_2_receitas.git')
                          }
                          branch('main')
                      }
                  }
                  scriptPath('Jenkinsfile')
              }
          }
      }